 const product=[
    {
        "no": 1,
        "id": "c1",
        "productname": "hp 250 g8",
        "productprice": 325000,
        "productinfo": "hp 250 g8 10th generation laptop",
        "productimage1": "/skydome images/hp-250-g8-img1.jpeg",
        "productimage2": "/skydome images/hp-250-g8-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "hp",
        "batteryinfo": "45watt li-on battery",
        "ram": "8gb",
        "rom": "1tbhdd",
        "windowversion": "windows 10 pro",
        "color": "silver",
        "touchscreen": "no",
        "netweight": "1.3kg",
        "inch": "15",
        "gaminggraphics": "2gb dedicated gaming graphics",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"hp 250 g8 laptop 8gb ram 1tb hdd windows 10pro core i5"
	
    },
    {
        "no": 3,
        "id": "c2",
        "productname": "lenovo legion 5",
        "productprice": 650000,
        "productinfo": "lenovo legion 5 15IMH05 10th generation laptop",
        "productimage1": "/skydome images/lenovo-legion-5-img1.png",
        "productimage2": "/skydome images/lenovo-legion-5-img2.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "lenovo",
        "batteryinfo": "integrated 60Wh",
        "ram": "8gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10 home",
        "color": "black",
        "touchscreen": "no",
        "netweight": "1.3kg",
        "inch": "15.6",
        "gaminggraphics": "NVIDIA GTX 4GB GDDR6",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"lenovo legion 5 core i5 8gb ram 512gb 4gb nivida win..."
    },
    {
        "no": 4,
        "id": "c3",
        "productname": "mac book pro",
        "productprice": 1395000,
        "productinfo": "apple mac book pro 16\" AMD Raedon Pro 5500M",
        "productimage1": "/skydome images/mac-book-pro-img2.jpeg",
        "productimage2": "/skydome images/mac-book-pro-img1.jpeg",
        "processortype": "intel",
        "processorname": "corei9",
        "brand": "Apple",
        "batteryinfo": "96W USB-C power adapter Up to 11 hours battery life",
        "ram": "16gb",
        "rom": "1tb ssd",
        "windowversion": "mac os",
        "color": "space grey",
        "touchscreen": "no",
        "netweight": "2kg",
        "inch": "14.09",
        "gaminggraphics": "AMD Radeon Pro 5500M graphics card With 4GB of GDDR6 VRAM",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"apple mac book pro touch bar core i9 16gb 1tb ssd AMD..."
    },
    {
        "no": 6,
        "id": "c4",
        "productname": "acer predator helios",
        "productprice": 810000,
        "productinfo": "acer predator helios 300",
        "productimage1": "/skydome images/acer-predator-helios-img2.jpeg",
        "productimage2": "/skydome images/acer-predator-helios-img1.jpeg",
        "processortype": "intel",
        "processorname": "corei7",
        "brand": "Acer",
        "batteryinfo": "Average Battery Life (in hours) ?6 Hours",
        "ram": "16gb",
        "rom": "512gb ssd",
        "windowversion": "windows 10",
        "color": "black",
        "touchscreen": "no",
        "netweight": "2.5kg",
        "inch": "15.6",
        "gaminggraphics": "Dedicated NVIDIA GeForce RTX 3060 6GB",
        "network": null,
        "frontcamera": null,
        "rearcamera": null,
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"acer predator helios 300 corei7 16gb ram,..."
    },
    {
        "no": 47,
        "id": "c8",
        "productname": "infinix s5 pro",
        "productprice": 87000,
        "productinfo": null,
        "productimage1": "/skydome images/infinix-s5-pro-img2.jpeg",
        "productimage2": "/skydome images/infinix-s5-pro-img1.jpeg",
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": "4000mAh",
        "ram": "6gb",
        "rom": "128gb",
        "windowversion": "android version 10",
        "color": "blue",
        "touchscreen": null,
        "netweight": null,
        "inch": "6.53",
        "gaminggraphics": null,
        "network": "4G LTE",
        "frontcamera": "40MP",
        "rearcamera": "48MP/2MP/QVGA",
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"infinix s5 pro 6.53' 6gb ram,12gb rom 4000mAh 40mp"
    },
    {
        "no": 9,
        "id": "c5",
        "productname": "Iphone 12 pro max",
        "productprice": 630000,
        "productinfo": null,
        "productimage1": "/skydome images/iphone-12promax-img2.jpeg",
        "productimage2": "/skydome images/iphone-12promax-img1.jpeg",
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": "3687mAh",
        "ram": "6gb",
        "rom": "256gb",
        "windowversion": "iOS 14.1",
        "color": "graphite",
        "touchscreen": null,
        "netweight": null,
        "inch": "6.7",
        "gaminggraphics": null,
        "network": "5G",
        "frontcamera": "12MP",
        "rearcamera": "(12MP+12MP+12MP)",
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"iphone 12 pro max 256gb 6gb ram 6.7 inch (12mp+12mp+12mp)"
    },
    {
        "no": 10,
        "id": "c6",
        "productname": "samsung galaxy s21 ultra samsung galaxy s21 ultrasamsung galaxy s21 ultra",
        "productprice": 619000,
        "productinfo": null,
        "productimage1": "/skydome images/samsung-galaxy-s21-img2.jpeg",
        "productimage2": "/skydome images/samsung-galaxy-s21-img1.jpeg",
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": "5000mAh",
        "ram": "12gb",
        "rom": "256gb",
        "windowversion": "android version 11 with one ui3.1",
        "color": "black",
        "touchscreen": null,
        "netweight": null,
        "inch": "6.6",
        "gaminggraphics": null,
        "network": "5G",
        "frontcamera": "40MP",
        "rearcamera": "12MP Ultra Wide Camera, 108MP Wide-angle Camera, Double 10MP Telephoto Camera",
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"samsung galaxy s21 256gb 12gbram 5g phantom black"
    },
    {
        "no": 12,
        "id": "c7",
        "productname": "samsung galaxy M51",
        "productprice": 195000,
        "productinfo": null,
        "productimage1": "/skydome images/samsung-galaxy-m51-img2.jpeg",
        "productimage2": "/skydome images/samsung-galaxy-m51-img1.jpeg",
        "processortype": null,
        "processorname": null,
        "brand": null,
        "batteryinfo": "7000mAh",
        "ram": "8gb",
        "rom": "128gb",
        "windowversion": "android version 10",
        "color": "blue",
        "touchscreen": null,
        "netweight": null,
        "inch": "6.7",
        "gaminggraphics": null,
        "network": "4G LTE",
        "frontcamera": "32MP",
        "rearcamera": "(64MP+12MP+5MP+5MP)",
        "shoesize": null,
        "quantity":1,
        "productinfopreview":"samsung galaxy m51 7000mah 8gb ram 12gb rom,android 10"
    }
]

export default product